#!/bin/sh

dos2unix() {
    for file in "$@"; do
        sed 's/\r$//' "$file" > "$file.out"
        mv "$file.out" "$file"
    done
}

if [ $# -lt 1 ]; then
	echo "usage: $(basename "$0") files"
else
	dos2unix "$*"
fi
