#!/bin/bash

usage () {
	echo "usage: man2pdf command"
}

create_pdf () {
	man -t "$manpage" > /tmp/"${manpage}".ps && ps2pdf /tmp/"${manpage}".ps
	if [ $? -ne 0 ]
	then
		## even if the ${manpage} man page doesn't exist
		## /tmp/${manpage}.ps would have been created, so tidy-up
		rm -f /tmp/"${manpage}".ps
		exit 1
	else
		## remove temporary file
		rm -f /tmp/"${manpage}".ps
	fi
}

manpage=$1

if [ "$manpage" == "" ]
then
	usage
	exit 2
fi

if [ -f "${manpage}".pdf ]
then
	read -p "${manpage}.pdf file exists, do you want to replace it? " ans_yn
	case "$ans_yn" in
		[Yy]|[Yy][Ee][Ss]) echo "Replacing ${manpage}.pdf ...";;
		*) exit 3;;
	esac
fi

create_pdf

